# Generated by Django 4.0.6 on 2023-10-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='challenger',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
