# Generated by Django 4.0.6 on 2023-10-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challenger_confirmation_code_challenger_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='national_code',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='challenger',
            name='university',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
