# Generated by Django 4.0.6 on 2023-10-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_challenger_national_code_challenger_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
