# Generated by Django 4.1.13 on 2024-10-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_challenger_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenger',
            name='is_workshop_attender',
        ),
    ]
