# Generated by Django 4.1.13 on 2024-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_challenger_is_workshop_attender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenger',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
