# Generated by Django 4.1.13 on 2024-10-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_group_judge_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('J', 'Junior'), ('S', 'Senior'), ('P', 'Pro')], default='J', max_length=1),
        ),
    ]
